version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  waf:
    links:
    - app
    depends_on:
    - app
    build: waf
    ports:
        - "80:80"
  app: # name of the first service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build: . # specify the directory of the Dockerfile
    environment:
      - MONGO_URL=mongodb://database/mean-app
    links:
      - database
    depends_on:
      - database
  database: # name of the third service
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: mongo # specify image to build container from
    volumes: 
      - "/data/db:/data/db"
    ports:
      - "27017:27017" # specify port forewarding
  logspout:
    image: gliderlabs/logspout:latest
    networks:
      - logging
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: 
      # Add logging url
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.20'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
networks:
  logging: